version: '3.8'

services:
  backend:
    build:
      context: ./src/app/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./src/app/frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
